### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by Jme7** [Kotuye/gyakorlat0.1#1]
I was wondering if I could help? This looks like a start to an interesting project.

**Comment by Kotuye** [comment]
Thanks.
I am now studying corporate web development.
As part of Git, I forked your material.
I will examine your work for my own development.

Jme7 <notifications@github.com> ezt írta (időpont: 2020. júl. 21., K,
23:38):

**Comment by Jme7** [comment]
Forking my stuff is fine, as long as no one trys to pretend that that was they're work :) I love open source, with credit.

**Comment by Jme7** [comment]
Oh, Kotuye? Every once in a while, if you haven't already made changes, I am going to send a pull request so that that site is updated. Is that ok? If you don't want me to, just say so.

**Comment by Kotuye** [comment]
I will search for my exam.

Jme7 <notifications@github.com> ezt írta (időpont: 2020. júl. 21., K,
23:38):

**Comment by Jme7** [comment]
Fun fact, if you make a repository that is named whatever your username is (so, Kotuye) you will get a special repository, and its readme.md will be on the top of your profile page!

**Comment by Kotuye** [comment]
Szerintem, most még nem. Még az alapoktat tanulom.
A nyelvet is most kezdtem.
/* I don't think so yet. I'm even learning the basics. I just started the
language. */

Jme7 <notifications@github.com> ezt írta (időpont: 2020. júl. 21., K,
23:38):

**Comment by Jme7** [comment]
Ok

**Comment by Jme7** [comment]
I am inviting you to The JC (not a REAL organization, but a kind of team), if you want
